### PR TITLE
Repaired requests leaking between fixtures

### PR DESCRIPTION
**Pull request by twolfson**
We are finally starting to use `httpretty-fixtures` internally and we caught our first major bug. There was a problem where all requests were being passed to the last fixture due to a pass-by reference for our `fixture` variable. In this PR:
- Added regression test for leaking requests between fixtures
- Repaired leaking requests by adding a closure

/cc @brettlangdon

### CODE REVIEW

**Comment by brettlangdon** [comment]
:+1 great catch.

**Comment by twolfson** [comment]
It's not much of a catch when it's causing tests to fail =P

**Comment by brettlangdon** [comment]
Well good fix for being blind sided?

**Comment by twolfson** [comment]
Aw, thanks =P

**Pull request merged**
